// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0J3HWLjKdIE2dPFVJdBjruFkTN-ZwKsE',
    appId: '1:574838944172:web:0fdf58eea2f8c9f4c5ca09',
    messagingSenderId: '574838944172',
    projectId: 'deringapp-67494',
    authDomain: 'deringapp-67494.firebaseapp.com',
    storageBucket: 'deringapp-67494.firebasestorage.app',
    measurementId: 'G-6BXXVVY1H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCreKGDKKxck3RWU3ujYQpq5nsHA6rLGeo',
    appId: '1:574838944172:android:d7afc880ad1d6186c5ca09',
    messagingSenderId: '574838944172',
    projectId: 'deringapp-67494',
    storageBucket: 'deringapp-67494.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh_n8rGVJJl7hm8zCLvtvbVLtZh4ffNNM',
    appId: '1:574838944172:ios:41cbd45c016d8e49c5ca09',
    messagingSenderId: '574838944172',
    projectId: 'deringapp-67494',
    storageBucket: 'deringapp-67494.firebasestorage.app',
    iosBundleId: 'com.example.magicStrikeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh_n8rGVJJl7hm8zCLvtvbVLtZh4ffNNM',
    appId: '1:574838944172:ios:41cbd45c016d8e49c5ca09',
    messagingSenderId: '574838944172',
    projectId: 'deringapp-67494',
    storageBucket: 'deringapp-67494.firebasestorage.app',
    iosBundleId: 'com.example.magicStrikeFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0J3HWLjKdIE2dPFVJdBjruFkTN-ZwKsE',
    appId: '1:574838944172:web:99d690dda3d1330fc5ca09',
    messagingSenderId: '574838944172',
    projectId: 'deringapp-67494',
    authDomain: 'deringapp-67494.firebaseapp.com',
    storageBucket: 'deringapp-67494.firebasestorage.app',
    measurementId: 'G-EHNKLBCQ3Y',
  );
}
