include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    deprecated_member_use: ignore
    prefer_final_fields: ignore
    prefer_interpolation_to_compose_strings: ignore
    unused_field: ignore
    unused_local_variable: ignore
    use_build_context_synchronously: ignore
