name: magic_strike_flutter
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2
  flutter_launcher_icons: ^0.9.2
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: IstokWeb
      fonts:
        - asset: assets/fonts/IstokWeb-Regular.ttf
        - asset: assets/fonts/IstokWeb-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/MyLogoRing.png'
