name: magic_strike_flutter
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2
  flutter_launcher_icons: ^0.9.2
  font_awesome_flutter: ^10.6.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  intl: ^0.18.1
  url_launcher: ^6.3.1
  collection: ^1.18.0
  package_info_plus: ^5.0.1
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0
  permission_handler: ^11.3.0
  # vibration: ^1.7.4  # Will be replaced by haptic_feedback for better stability
  haptic_feedback: ^0.4.2
  device_info_plus: ^9.1.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  # Temporarily commenting out fonts until we have the files
  # fonts:
  #   - family: IstokWeb
  #     fonts:
  #       - asset: assets/fonts/IstokWeb-Regular.ttf
  #       - asset: assets/fonts/IstokWeb-Bold.ttf
  #         weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/MyLogoRing.png'
